import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TokenProvider } from "./context/TokenContext";
import { DataProvider } from "./context/DataContext";
import { IdProvider } from "./context/IdContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-secondary `}
      >
        <IdProvider>
          <TokenProvider>
            <DataProvider>
              {children}
            </DataProvider>
          </TokenProvider>
        </IdProvider>
      </body>
    </html>
  );
}
